version: '3.8'
services:
  ansible:
    build: playbook
    environment:
      - CRON
      - HOST
      - SSH_KEY
      - SSH_USER
    image: ghcr.io/jshbrntt/speed-monitor-pi:latest
    network_mode: host
    volumes:
      - ${SSH_KEY}:/root/.ssh/id_rsa
      - ./playbook/ssh/config:/root/.ssh/config
      - ./playbook:/root/playbook
