apiVersion: 1

datasources:
- name: InfluxDB
  type: influxdb
  uid: influxdb
  url: http://localhost:8086
  editable: true
  isDefault: true
  version: 1
  jsonData:
    defaultBucket: $INFLUXDB_BUCKET
    httpMode: POST
    organization: $INFLUXDB_ORG
    version: Flux
    readOnly: true
  secureJsonData:
    token: $INFLUXDB_TOKEN
